### ISSUE TITLE
Cannot run dashboard

### ISSUE THREAD

**Issue by pierrepo** [data-fun/3d-scere#9]
After creating and loading the conda env, having the required files and running the dashboard with:

```
python app.py
```

I get the following error message:
```
Traceback (most recent call last):
  File "/home/pierre/.soft/miniconda3/envs/dashboard/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pierre/.soft/miniconda3/envs/dashboard/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pierre/.soft/miniconda3/envs/dashboard/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pierre/.soft/miniconda3/envs/dashboard/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pierre/.soft/miniconda3/envs/dashboard/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pierre/.soft/miniconda3/envs/dashboard/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pierre/.soft/miniconda3/envs/dashboard/lib/python3.8/site-packages/dash/dash.py", line 1078, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/home/pierre/.soft/miniconda3/envs/dashboard/lib/python3.8/site-packages/dash/dash.py", line 1009, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "app.py", line 762, in update_metrics_1
    subgraph_edges = pd.json_normalize(subgraph_edges['data'])
  File "/home/pierre/.soft/miniconda3/envs/dashboard/lib/python3.8/site-packages/pandas/core/frame.py", line 3455, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/pierre/.soft/miniconda3/envs/dashboard/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'data'
127.0.0.1 - - [31/Aug/2021 14:47:42] "POST /_dash-update-component HTTP/1.1" 500 -
```

The web page obtained at <http://127.0.0.1:8050/> says `Error loading dependencies`

**Comment by Thibault-Poinsignon** [comment]
There is two things here:
- the error message come from a callback with not yet an object.  When you activate the tab 3 SUBMIT button, the log message stop spamming at each interaction with the dashboard.
- I corrected the path to the SQL database that was obsolete in this repository (./ instead of ../). Maybe this will correct the `Error loading dependencies`.

**Comment by pierrepo** [comment]
OK. Thanks. But I cannot even run the dashboard and display it on my browser. Is it something expected?
When tracing back the error message, I found this:

```
  File "app.py", line 788, in update_metrics_3
    subgraph_edges = pd.json_normalize(subgraph_edges['data'])
  File "/home/pierre/.soft/miniconda3/envs/dashboard/lib/python3.8/site-packages/pandas/core/frame.py", line 3455, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/pierre/.soft/miniconda3/envs/dashboard/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'data'
```
It looks like there's something wrong at line 788 of `app.py`:
```
    subgraph_edges = pd.json_normalize(subgraph_edges['data'])
```
Could you fix this or disable the tab 3?

**Comment by Thibault-Poinsignon** [comment]
> Is it something expected?
No, you only have `Error loading dependencies` right? I forgot to push the path correction before and just did it. Can you try again please?

> It looks like there's something wrong at line 788 of app.py
It is the callback without object (yet) I was talking about. It is not responsible for the dashboard not launching on your computer.

**Comment by pierrepo** [comment]
> No, you only have `Error loading dependencies` right?

Yes.

> I forgot to push the path correction before and just did it. Can you try again please?

No worries. I updated the repo and ran the dashboard. Still a blank page. The status icon is spinning and displays `Updating...`, but nothing eventually displayed in the web browser. How long does it usually take to load the app on your computer?

Did you check the app is running on a clean new conda env? Save yours before with:
```
conda env export -n dashboard --no-builds  | grep -v "^prefix:" > dashboard_old.yml
```

**Comment by Thibault-Poinsignon** [comment]
> How long does it usually take to load the app on your computer?

Not long at all.

> Did you check the app is running on a clean new conda env?

I will !

**Comment by Thibault-Poinsignon** [comment]
@pierrepo, I think i found the problem. When creating a new environment, there is a conflict:
`Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - dash-bootstrap-components
  - dash_cytoscape
`
When using the extended .yml of my old environment (with version numbers), the issue is solved. Since I pushed this version of the .yml, your dashboard should launch correctly now.

**Comment by pierrepo** [comment]
Thanks you @Thibault-Poinsignon It's working now :tada: 

![image](https://user-images.githubusercontent.com/733861/131531025-204ab0fc-a4f5-4b54-a9c6-2f3d38418d18.png)

However, for development purpose, we need a conda env file with a minimal set of dependencies. This will be handled in issue
https://github.com/data-fun/3d-scere/issues/14
